/* S -> T */

CREATE TABLE transducer._PERSON_INSERT AS
SELECT * FROM transducer._PERSON
WHERE 1<>1;

CREATE TABLE transducer._PERSON_DELETE AS
SELECT * FROM transducer._PERSON
WHERE 1<>1;


CREATE TABLE transducer._PERSON_INSERT_JOIN AS
SELECT * FROM transducer._PERSON
WHERE 1<>1;

CREATE TABLE transducer._PERSON_DELETE_JOIN AS
SELECT * FROM transducer._PERSON
WHERE 1<>1;






/** INSERT T -> S **/

CREATE TABLE transducer._P_INSERT AS
SELECT * FROM transducer._P
WHERE 1<>1;

CREATE TABLE transducer._P_DELETE AS
SELECT * FROM transducer._P
WHERE 1<>1;

CREATE TABLE transducer._PE_INSERT AS
SELECT * FROM transducer._PE
WHERE 1<>1;

CREATE TABLE transducer._PE_DELETE AS
SELECT * FROM transducer._PE
WHERE 1<>1;

CREATE TABLE transducer._PED_INSERT AS
SELECT * FROM transducer._PED
WHERE 1<>1;

CREATE TABLE transducer._PED_DELETE AS
SELECT * FROM transducer._PED
WHERE 1<>1;

CREATE TABLE transducer._PE_HDATE_INSERT AS
SELECT * FROM transducer._PE_HDATE
WHERE 1<>1;

CREATE TABLE transducer._PE_HDATE_DELETE AS
SELECT * FROM transducer._PE_HDATE
WHERE 1<>1;

CREATE TABLE transducer._PED_DEPT_INSERT AS
SELECT * FROM transducer._PED_DEPT
WHERE 1<>1;

CREATE TABLE transducer._PED_DEPT_DELETE AS
SELECT * FROM transducer._PED_DEPT
WHERE 1<>1;

CREATE TABLE transducer._DEPT_MANAGER_INSERT AS
SELECT * FROM transducer._DEPT_MANAGER
WHERE 1<>1;

CREATE TABLE transducer._DEPT_MANAGER_DELETE AS
SELECT * FROM transducer._DEPT_MANAGER
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_INSERT AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_DELETE AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_INSERT AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_DELETE AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;


CREATE TABLE transducer._P_INSERT_JOIN AS
SELECT * FROM transducer._P
WHERE 1<>1;

CREATE TABLE transducer._P_DELETE_JOIN AS
SELECT * FROM transducer._P
WHERE 1<>1;

CREATE TABLE transducer._PE_INSERT_JOIN AS
SELECT * FROM transducer._PE
WHERE 1<>1;

CREATE TABLE transducer._PE_DELETE_JOIN AS
SELECT * FROM transducer._PE
WHERE 1<>1;

CREATE TABLE transducer._PED_INSERT_JOIN AS
SELECT * FROM transducer._PED
WHERE 1<>1;

CREATE TABLE transducer._PED_DELETE_JOIN AS
SELECT * FROM transducer._PED
WHERE 1<>1;

CREATE TABLE transducer._PE_HDATE_INSERT_JOIN AS
SELECT * FROM transducer._PE_HDATE
WHERE 1<>1;

CREATE TABLE transducer._PE_HDATE_DELETE_JOIN AS
SELECT * FROM transducer._PE_HDATE
WHERE 1<>1;

CREATE TABLE transducer._PED_DEPT_INSERT_JOIN AS
SELECT * FROM transducer._PED_DEPT
WHERE 1<>1;

CREATE TABLE transducer._PED_DEPT_DELETE_JOIN AS
SELECT * FROM transducer._PED_DEPT
WHERE 1<>1;

CREATE TABLE transducer._DEPT_MANAGER_INSERT_JOIN AS
SELECT * FROM transducer._DEPT_MANAGER
WHERE 1<>1;

CREATE TABLE transducer._DEPT_MANAGER_DELETE_JOIN AS
SELECT * FROM transducer._DEPT_MANAGER
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_INSERT_JOIN AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_DELETE_JOIN AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_INSERT_JOIN AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_DELETE_JOIN AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;



CREATE TABLE transducer._LOOP (
loop_start INT NOT NULL );