/** S->T INSERT TRIGGERS **/

CREATE TRIGGER source_PERSON_INSERT_trigger
AFTER INSERT ON transducer._PERSON
FOR EACH ROW
EXECUTE FUNCTION transducer.source_PERSON_INSERT_fn();

CREATE TRIGGER source_PERSON_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PERSON_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.source_PERSON_INSERT_JOIN_fn();

CREATE TRIGGER source_INSERT_trigger_1
AFTER INSERT ON transducer._PERSON_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_INSERT_fn();




/** T->S INSERT **/

CREATE TRIGGER target_P_INSERT_trigger
AFTER INSERT ON transducer._P
FOR EACH ROW
EXECUTE FUNCTION transducer.target_P_INSERT_fn();

CREATE TRIGGER target_PE_INSERT_trigger
AFTER INSERT ON transducer._PE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PE_INSERT_fn();

CREATE TRIGGER target_PE_HDATE_INSERT_trigger
AFTER INSERT ON transducer._PE_HDATE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PE_HDATE_INSERT_fn();

CREATE TRIGGER target_PED_INSERT_trigger
AFTER INSERT ON transducer._PED
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PED_INSERT_fn();

CREATE TRIGGER target_PED_DEPT_INSERT_trigger
AFTER INSERT ON transducer._PED_DEPT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PED_DEPT_INSERT_fn();

CREATE TRIGGER target_DEPT_MANAGER_INSERT_trigger
AFTER INSERT ON transducer._DEPT_MANAGER
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DEPT_MANAGER_INSERT_fn();

CREATE TRIGGER target_PERSON_PHONE_INSERT_trigger
AFTER INSERT ON transducer._PERSON_PHONE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_INSERT_fn();

CREATE TRIGGER target_PERSON_EMAIL_INSERT_trigger
AFTER INSERT ON transducer._PERSON_EMAIL
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_INSERT_fn();




CREATE TRIGGER target_P_INSERT_JOIN_trigger
AFTER INSERT ON transducer._P_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_P_INSERT_JOIN_fn();

CREATE TRIGGER target_PE_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PE_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PE_INSERT_JOIN_fn();

CREATE TRIGGER target_PE_HDATE_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PE_HDATE_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PE_HDATE_INSERT_JOIN_fn();

CREATE TRIGGER target_PED_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PED_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PED_INSERT_JOIN_fn();

CREATE TRIGGER target_PED_DEPT_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PED_DEPT_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PED_DEPT_INSERT_JOIN_fn();

CREATE TRIGGER target_DEPT_MANAGER_INSERT_JOIN_trigger
AFTER INSERT ON transducer._DEPT_MANAGER_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DEPT_MANAGER_INSERT_JOIN_fn();

CREATE TRIGGER target_PERSON_PHONE_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PERSON_PHONE_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_INSERT_JOIN_fn();

CREATE TRIGGER target_PERSON_EMAIL_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PERSON_EMAIL_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_INSERT_JOIN_fn();





CREATE TRIGGER target_INSERT_trigger_1
AFTER INSERT ON transducer._P_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_2
AFTER INSERT ON transducer._PE_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_3
AFTER INSERT ON transducer._PE_HDATE_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_4
AFTER INSERT ON transducer._PED_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_5
AFTER INSERT ON transducer._PED_DEPT_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_6
AFTER INSERT ON transducer._DEPT_MANAGER_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_7
AFTER INSERT ON transducer._PERSON_PHONE_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_8
AFTER INSERT ON transducer._PERSON_EMAIL_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();


